(()=>{var m=["sisters","parent","children","farm"];var k={sisters:"Sisters",parent:"Parent",children:"Children",farm:"Farm",neighbourhood:"Neighbourhood",snapshot:"Snapshot"},w=e=>(e||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\*(.+?)\*/g,"<i>$1</i>"),S=e=>{let t=Math.floor(e/1e3),o=1.9,n="a minute ago";return t>o*60&&(n=`${Math.round(t/60)} minutes ago`),t>o*3600&&(n=`${Math.round(t/3600)} hours ago`),t>o*86400&&(n=`${Math.round(t/86400)} days ago`),t>o*604800&&(n=`${Math.round(t/604800)} weeks ago`),t>o*2592e3&&(n=`${Math.round(t/2592e3)} months ago`),t>o*31536e3&&(n=`${Math.round(t/31536e3)} years ago`),n},x=e=>{if(!e)return"";let t=e.map(o=>o.date).filter(o=>typeof o=="number");return t.length?S(Date.now()-Math.max(...t)):""},E=()=>[80,"80","",null].includes(location.port)?"":`:${location.port}`,N={FAMILY:["parent","sisters"],SISTERS:"sisters",PARENT:"parent",CHILDREN:"children",FARM:"farm",NEIGHBOURHOOD:"neighbourhood",NEIGHBORHOOD:"neighbourhood",SNAPSHOT:"snapshot"},R=e=>(e||"").split(`
`).some(t=>t.trim().split(/\s+/)[0].replace(/:$/,"").toUpperCase()==="FREEZE"),I=e=>{let t=[];for(let o of(e||"").split(`
`)){let n=o.trim();if(!n)continue;let p=n.split(/\s+/)[0].replace(/:$/,"").toUpperCase(),l=N[p];if(l)for(let d of[].concat(l))t.includes(d)||t.push(d)}return t.length?t:["sisters"]},b=(e,t,o)=>{let n=E(),p=e.split(".")[0],l=`<img class=remote title="${e}${n}" src="//${e}${n}/favicon.png" data-site="${e}${n}" data-slug=welcome-visitors>`;return`<tr><td align=right>${p} ${l}<td data-site="${e}${n}">${t} pages ${x(o)}`},y=(e,t)=>`<p class=caption><b>${k[e]}</b></p><table width=100% class=family-${e}>${t.join(`
`)}</table>`,O=(e,t)=>{let o=E(),n=I(t.text),p=R(t.text),l={};if(e.closest(".page").hasClass("remote")){e.html(`<div class=family style="background-color:#eee;padding:15px"><center>${w(t.text)}<p class=caption>Family is only available when viewed on a page's home wiki.</p></div>`);return}e.html(`<div class=family style="background-color:#eee;padding:15px"><center>${w(t.text)}<p class=caption>gathering\u2026</p><div class=groups></div></div>`);let d=c=>{let f=[];for(let a of n)if(m.includes(a)){let i=c[a]||[];l[a]=i.map(s=>s.site);let r=i.map(s=>(wiki.neighborhoodObject.registerNeighbor(s.site+o),b(s.site,s.pages,wiki.neighborhood[s.site+o]?.sitemap)));f.push(y(a,r.length?r:["<tr><td><i>none</i>"]))}else{let i=Object.keys(wiki.neighborhood);l[a]=i;let r=i.map(s=>{let h=wiki.neighborhood[s]?.sitemap;return b(s,h?h.length:0,h)});f.push(y(a,r.length?r:["<tr><td><i>empty</i>"]))}if(e.find(".groups").html(f.join(`
`)),e.find(".caption").first().text("just updated"),p){let a=location.hostname.split(".")[0],i=$('<button class=family-freeze style="margin-top:8px;padding:4px 12px;cursor:pointer;font-size:13px">\u2744 Freeze</button>');i.on("click",()=>{let r=()=>Math.floor(Math.random()*0xffffffffffff).toString(16).padStart(12,"0"),s=[{type:"markdown",id:r(),text:`# ${a} Family`}];for(let u of n){let M=l[u]||[];s.push({type:"roster",id:r(),text:`${k[u]} Wikis

${M.join(`
`)||"(none)"}`})}let h=wiki.newPage({title:`${a} Family`,story:s});wiki.showResult(h,{$page:e.parents(".page")})}),e.find(".family").append(i)}$("body").on("new-neighbor-done",(a,i)=>{let r=e.find(`td[data-site="${i}"]`);if(!r.length)return;let s=wiki.neighborhood[i]?.sitemap;s&&r.text(`${s.length} pages ${x(s)}`)})},g=n.filter(c=>m.includes(c));if(g.length===0){d({});return}fetch(`/plugin/family/roll?kinds=${encodeURIComponent(g.join(","))}`).then(c=>{if(!c.ok)throw new Error(`HTTP ${c.status}`);return c.json()}).then(c=>d(c.groups||{})).catch(()=>e.find(".caption").first().text("server error"))},F=(e,t)=>{e.dblclick(()=>wiki.textEditor(e,t))};typeof window<"u"&&(window.plugins=window.plugins||{},window.plugins.family={emit:O,bind:F});})();
//# sourceMappingURL=family.js.map
